# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle


# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
default:
  image: openjdk:8.0-slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - test
  - package
  - deploy
  - systemtest

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

test:
  image: gradle:latest
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - ./build/libs/gitlabcicd-0.0.1-SNAPSHOT.jar 


package:
   image: docker:latest
   services:
     - docker:dind
   stage: package
   script:
     - docker build -t steinko/gitlabcicd .
     - docker login -u steinko -p RoxyMusic11
     - docker push steinko/gitlabcicd


deploy:
  stage: deploy
  before_script:
    - chmod +x ./infAsCode/scripts/*.sh
    - apk update
    - apk add bash
    - apk add curl
    - ./infAsCode/scripts/setup.sh
  script:
    - ./infAsCode/scripts/run-pulumi.sh
  # Create an artifact archive with just the pulumi log file,
  # which is created using console-redirection in run-pulumi.sh.
  artifacts:
    paths:
    - pulumi-log.txt
    # This is just a sample of how artifacts can be expired (removed) automatically in GitLab.
    # You may choose to not set this at all based on your organization's or team's preference.
    expire_in: 1 week